
version: '2'
services:

  # The Application
  globaleaks:
    container_name: alac-gl
    build:
      context: ./
      dockerfile: appgl.dockerfile
    working_dir: /data/globaleaks
    image: globaleaks/globaleaks
    volumes:
       - ./alac-gl/gl_data:/var/globaleaks/
    ports:
      - '80:80'
      - '443:443'
  app:
    container_name: alac-dashboard
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /data/alac
    volumes:
      - ./alac-dashboard:/data/alac
    environment:
      DB_PORT: 5432
      AWS_KEY: AKIASP5UVE556LUBKIEP
      AWS_ACCESS: 2xI4h9Zrp8waIxOMwjzXf0QuE4cYoMjTUbykgGsQ
      AWS_BUCKET: alact
    ports:
      - 5000:5000
      - 3000:3000
    volumes_from:
      - globaleaks
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: postgres
    volumes:
      - ./dbdata/database/:/var/lib/postgresql/data
