source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'devise'
gem 'rails', '~> 5.1.6', '>= 5.1.6.1' # Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'neat', '~> 1.0' # A lightweight semantic grid framework for Sass and Bourbon.
gem 'pg' # Use postgresql as the database for Active Record
gem 'puma', '~> 3.7' # Use Puma as the app server
gem 'slim-rails' # Template language
gem 'sass-rails', '~> 5.0' # Use SCSS for stylesheets
gem 'uglifier', '>= 1.3.0' # Use Uglifier as compressor for JavaScript assets
gem 'webpacker' # Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker

gem 'sqlite3'
gem "administrate", '~> 0.12.0'
gem 'kaminari'
gem 'xlsxtream'
gem 'pry', '~> 0.12.2'
gem "better_errors"
gem "binding_of_caller"
gem 'carrierwave', '~> 2.0'
gem 'carrierwave-aws'
group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw] # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'capybara', '~> 2.13' # Adds support for Capybara system testing and selenium driver
  gem 'selenium-webdriver'
  gem 'foreman'

end

group :development do
  gem 'web-console', '>= 3.3.0' # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring' # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring-watcher-listen', '~> 2.0.0'

end

gem 'tzinfo-data' # Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'bootstrap', '~> 4.3.1'
gem 'bootstrap-select-rails'
