module ActorsOptionsHelper
  def get_options
    {
      'individual_actor_types' => [
        'Actor privado con funciones públicas por colaboración',	
        'Actor vinculado a economía ilegal', 	
        'Altos dignatarios',		
        'Autoridad Electa por votación propular',	
        'Director/Trabajador caja de compensación familiar', 	
        'Miembro de Grupo armado ilegal', 	
        'Miembro de la fuerza pública',		
        'Miembro de partido político, movimiento y/o grupo significativo de ciudadanos', 	
        'Miembro del tercer Sector', 		
        'No aplica',	'No disponible',	
        'Otros',	
        'Servidores públicos	Con vínculo con el Estado por orden de prestación de servicios (OPS)'
      ],

      'individual_first_subtype' => [
        ['Actor privado con funciones públicas por colaboración', 
          ['Funcionario de la camara de comercio',
          'Notario']
        ],
        ['actor vinculado a economia ilegal', 
          ['Actor vinculado a contrabando',
          'Actor vinculado a minería ilegal', 
          'actor vinculado a redes de extorsión', 
          'Actor vinculado a tráfico de armas/personas',
          'narcotraficante']
        ],
        ['altos dignatarios', 
          ['Defensor del Pueblo',
          'Director de Corporación autónoma',
          'Director de cormagdalena',
          'Director de departamento/agencia',
          'Director de empresa de naturaleza de régimen especial',
          'gerente público',
          'Miembro de junta directiva (Banco de la República-Ecopetrol-fogafyn-Bancoldex-La previsora)',
          'Ministro',
          'órgano autónomo', 
          'Personero',
          'Rama Judicial',
          'Superintendente'
          ]
        ],
        ['Autoridad electa por votacion popular', 
          ['Alcalde',
          'Concejal',
          'Diputado',
          'Edil',
          'Gobernador',
          'Presidente',
          'Representante a la Camara',
          'Senador']
        ],
        ['Miembrp de grupo armado ilegal', 
          ['Miembro de delincuencia común o grupo delictivo organizado (GDO) Ley 1908 de 2018',
          'Miembro de Grupo Armado Organizado (GAO) Ley 1908 de 2018',
          'Miembro de Guerrilla'
          ]
        ],
        ['Miembro de la fuerza publica', 
          ['Fuerza armada', 'Policía']
        ],
        ['Miembro de partido político, movimiento y/o grupo significativo de ciudadanos',
          ['Candidato',
          'Director de partido/moviemiento/grupo',
          'Líder Político',
          'Militante',
          'No aplica',
          'No disponible',
          'Simpatizante'
          ]
        ],
        ['Miembro del tercer Sector',
          ['Ciudadano',
          'Miembro de consorcio', 
          'Miembro de corporación privada',
          'Miembro de Sociedad civil organizada',
          'Miembro de una fundación',
          'Miembro de una ONG',
          'Miembro de unión temporal',
          'otros'] 
        ],
        ['Servidores Publicos', 
          ['En carrera',
          'En provisionalidad',
          'Libre nombramiento y remoción']
        ]
      ],
      'individual_second_subtype' => [
        ['Organo autónomo', 
          ['Auditor', 
          'Contralor', 
          'Director de Universidad Estatal/Institución técnica y tecnológica',
          'Gerente del Banco de la República',
          'Procurador',
          'Registrador'],
        ],
        ['Rama Judicial', 
          ['Fiscal', 
          'Juez', 
          'Magistado',
          'Asistente de despacho',
          'Funcionario judicial']
        ],
        ['Fuerza Armada', 
          ['Alto rango',
          'Raso',
          'Alto rango',
          'Raso']
        ],
        ['Miembro de sociedad civil organizada', 
          ['ciudadano que realiza control social',
          'Miembro de una comunidad  y /o movimiento étnico',
          'Veedor ciudadano',
          'Presidente de Junta de Acción Comunal- JAC']
        ],
        ['otros', 
          ['Miembro de comunidad religiosa',
          'Miembro de medio de comunicación/periodista']
        ]
      ],

      'collective_actor_types'=> [
        'Actores vinculados a economía ilegal', 	
        'Empresas privadas	Entidades del Estado',		
        'Grupos armados ilegales', 	
        'Instituciones de la Fuerza Pública',	
        'No aplica',	
        'No disponible',	
        'Notaría',	
        'Otro',	
        'Organizaciones políticas',		
        'Tercer Sector',	
        'Agremiaciones',	
        'Empresas privadas con funciones públicas'
      ],

      'collective_first_subtype' => [
        'Bandas de minería ilegal',
        'Redes de contrabando',
        'Redes de extorsión',
        'Redes de narcotráfico',
        'Redes de tráficos de armas/personas',
        'Hospitales públicos',
        'Órganos autónomos',
        'Rama Ejecutiva', 
        'Rama Judicial',
        'Delincuencia común o grupo delictivo organizado (GDO) Ley 1908 de 2018',
        'Grupo Armado Organizado (GAO) Ley 1908 de 2018',
        'Guerrilla',
        'Fuerza Armada',
        'Policía',
        'Partido político',
        'Consorcio',
        'Corporación Privada',
        'Fundación',
        'ONG',
        'Otros',
        'Sociedad civil organizada',
        'Unión temporal',
        'Eps',
        'Cajas de compensación familiar',
        'AFP´s',
        'Universidades',
      ],

      'collective_second_subtype' => [
        'Contraloría General de la República',
        'Contralorías territoriales',
        'CorMagadalena',
        'Corporaciones autónomas y reginale',
        'Defensoría del Pueblo',
        'Departamento Público/Agencia',
        'Empresas Naturales del régimen especial',
        'Ministerio Público', 
        'Ministerios',
        'Personería (Distrital/Municipal)',
        'Procuraduría General de la Nación',
        'Procuradurías Regionales',
        'Registraduría Nacional del Estado Civil',
        'Superintendencias',
        'Universidades Estatales/Instituciones técnicas y tecnológicas',
        'Alcaldía', 
        'Asamblea departamental',
        'Concejo municipal/distrital',
        'Gobernación',
        'Consejo de Estado',
        'Consejo Superior de la Judicatura',
        'Corte Constitucional',
        'Corte Suprema de Justicia',
        'Fiscalía General de la Nación',
        'Jurisdicciones especiales /JEP',
        'Alianza Social independiente-ASI',
        'Autoridades Indígenas de Colombia-AICO',
        'Centro Democrático',
        'Grupos Significativos de ciudadanos',
        'Movimiento Alternativo  Indígena y Social- MAIS',
        'Movimiento Independiente de Renovación Absoluta- MIRA',
        'No aplica',
        'No disponible',
        'Opción Ciudadana', 
        'Otro/movimiento político',
        'Partido Alianza Verde',
        'Partido Cambio Radical',
        'Partido Conservador Colombiano', 
        'Partido de la U',
        'Partido FARC',
        'Partido Liberal Colombiano',
        'Polo Democrátivo Alternativo',
        'Unión Patriótica UP',
        'Congregación religiosa',
        'Medios de comunicación',
        'Comunidades y movimientos étnicos',
        'Veeduría ciudadana',
      ],
      'actors_institution' => [
        'Entidades Nacionales (nivel central)',
        'Entidades Nacionales – (nivel descentralizado)',
        'Entidades Departamentales – (nivel central)',
        'Entidades Departamentales – (nivel descentralizado)',
        'Entidades Municipales – (nivel central)',
        'Entidades Municipales – (nivel descentralizado)',
        'Corporaciones Autónomas Regionales',
        'Instituciones de Educación Oficial',
        'Órganos de Control',
        'Empresas e Instituciones Prestadoras de Salud –EPS',
        'Uniones temporales y consorcios',
        'Fundaciones, corporaciones cívicas, ONG, Asociaciones',
        'Empresas Privadas',
        'Organizaciones Políticas (partidos, movimientos, grupos significativos de ciudadanos)',
        'Organizaciones sociales y comunitarias (primer y segundo nivel)',
        'Instituciones privadas con funciones públicas (cajas de compensación, cámaras de comercio, notarias, curadurías urbanas)',
        'Entidades de la rama judicial (Fiscalía, juzgados, cárceles)',
        'Empresas con capital estatal',
        'Corporaciones Públicas',
        'Empresas Prestadoras de Servicios Públicos',
        'Medios de comunicación',
        'Sociedad de economía mixta',
        'Otros (Iglesias-Aeropuertos etc.)',
        'No disponible',
        'No aplica',
      ],
      'actors_position' => [
        '---',
        'Abogado',
        'Agente',
        'Alcalde',
        'Alto Dignatario',
        'Auditor',
        'Candidato a una elección',
        'Cargo Administrativo',
        'Cargo de Coordinación',
        'Cargo de Subdirección',
        'Cargo Directivo',
        'Cargo Gerencial',
        'Concejal',
        'Contador',
        'Contralor',
        'Contratista',
        'Diputado',
        'Edil',
        'Empleado de entidad educativa',
        'Empresario',
        'Fiscal',
        'Funcionario jurídico',
        'Funcionario EPS',
        'Funcionario público',
        'Gobernador',
        'Ingeniero',
        'Interventor',
        'Juez',
        'Líder Social',
        'Magistrado',
        'Miembro de la fuerza pública',
        'Miembro de Junta Directiva',
        'No Aplica- Este se da cuando responde a actor colectivo que no ocupa cargo',
        'No Disponible',
        'Otras profesiones ',
        'Personero',
        'Registrador',
        'Representante Legal',
        'Revisor Fiscal',
        'Secretario distrital',
        'municipal y/o departamental',
        'Senador',
        'Tesorero',
        'No Disponible',
        'No Aplica'
      ],
      'actors_public_branch' => [
        'Corporación Político Administrativa',
        'Fuerza Pública',
        'No aplica',
        'No disponible',
        'Organismos de control',
        'órganos electorales',
        'Otras Instituciones del Estado',
        'Rama Ejecutiva',
        'Rama Legislativa',
        'Rama Judicial'
      ],
      'actors_entity' => [
        'Alianza Social independiente-ASI',
        'Autoridades Indígenas de Colombia-AICO',
        'Centro Democrático',
        'Grupos Significativos de ciudadanos',
        'Movimiento Alternativo  Indígena y Social- MAIS',
        'Movimiento Independiente de Renovación Absoluta- MIRA',
        'No aplica',
        'No disponible',
        'Opción Ciudadana ',
        'Otro/movimiento político',
        'Partido Alianza Verde',
        'Partido Cambio Radical ',
        'Partido Conservador Colombiano ',
        'Partido de la U',
        'Partido FARC',
        'Partido Liberal Colombiano',
        'Polo Democrátivo Alternativo',
        'Unión Patriótica UP'
      ]
    }
  end
end
